#pragma config(Sensor, S1,     sonar,          sensorNone)
#pragma config(Sensor, S4,     button,         sensorNone)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	  motor(left) = 50;
	  motor(right) = 50;
	  wait1Msec(50);

	  if (SensorValue(sonar) > 10){
	  	motor(left) = 55;
	  	motor(right) = 50;
	  	wait1Msec(50);
	  }
	  else if(SensorValue(sonar) < 10){
	  	motor(left) = 50;
	  	motor(right) = 55;
	  	wait1Msec(50);
	  }
	  if(SensorValue(button) == 1){
	  	motor(left) = -40;
	  	motor(right) = -50;
	  	wait1Msec(1200);

	  	motor(left) = -50;
	  	motor(right) = 50;
	  	wait1Msec(875);
  	}
  }

}
