#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          sonarPeg,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float calcDrift()
{
	int totalDrift = 0;
	wait1Msec(500);
	for (int i = 0; i < 10; i ++)
	{
		wait1Msec(250);
		float totalDrift =  SensorValue(gyro) + totalDrift;
	}
	float avgDrift = totalDrift / 10.0;
	return avgDrift;
}

static float calcDegree(int degree)
{
   float time = degree * 3.26388888889;
   return time;
}

task main()
{
	wait1Msec(500);

  SensorType[S1] = sensorNone;
  wait1Msec(1000);
  SensorType[S1] = gyro;
  wait1Msec(1000);

  int drift = calcDrift();
  /*
  if (SensorValue(gyro) - drift > 10)
  {

  }
  */
  while (true)
  {
  if(SensorValueFloat(gyro) - drift  > 180 || SensorValueFloat(gyro) - drift  < -100 )
  {
  	  motor(sonarPeg) = 20;
  	  wait1Msec(calcDegree(SensorValue(gyro) - drift));
  }
}

}
