#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          sonarPeg,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
	int i = 0;
 while(i < 50)
 {
 motor(sonarPeg) = -20;
 wait1Msec(10);
 i ++;
}
while (i < 100 && i >= 50)
{
	 motor(sonarPeg) = 20;
 wait1Msec(10);
 i ++;
}
}
}
