#pragma config(Sensor, S1,     sonar,          sensorNone)
#pragma config(Sensor, S4,     button,         sensorNone)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int defaultSpeed = 50;
	while (SensorValue(sonar) < 50)
	{
		motor(left) = defaultSpeed;
		motor(right) = defaultSpeed;


			if (SensorValue(sonar) > 10)
			{
				motor(left) = defaultSpeed + 1;
				wait1Msec(50);
			}
			if (SensorValue(sonar) < 10)
			{
				motor(left) = defaultSpeed - 1;
				wait1Msec(50);
			}

			if (SensorValue(button) == 1)                //hi JAKE
			{
				motor(left)= -100;
				motor(right) = -100;
				wait1Msec(750);

				motor(left) = 50;
				motor(right) = -50;
				wait1Msec(875 / 2);
			}
	}
}
