#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     buttonTwo,      sensorEV3_Touch)
#pragma config(Sensor, S4,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	 int mode = 1;
	 int defSpeed = 50;
	 int exit = 1;


	 while (true)
 {
   if (mode == 0) // mode 0 is wall follow
   {

     resetMotorEncoder(left);
     resetMotorEncoder(right);
     int exitZero = 0;
	 	 while (exitZero == 0)
	 	 {
			 exitZero = 0;
			 motor(left) = defSpeed + 10;
			 motor(right) = defSpeed;


			 wait1Msec(250);

			 if(SensorValue(buttonTwo) == 1)
			 {
			   motor(left) = -defSpeed;
			   motor(right) = -defSpeed;
			   wait1Msec(500);

			   motor(left) = -defSpeed;
			   motor(right) = defSpeed;
			   wait1Msec(960 / 2);

			 }

			 if (SensorValue(button) == 1)
			 {
			   for( int i = 0; i < 10; i++)
			   {
				   motor(left) = -defSpeed + 2;
				   motor(right) = -defSpeed;
				   wait1Msec(50);

				 }
				  motor(left) = -defSpeed;
			   	motor(right) = defSpeed;
			    wait1Msec(960 / 2);
			 }

			 if(getMotorEncoder(left) + getMotorEncoder(right) >=  10000)
			 {
			   mode = 2;
			   exitZero = 1;
			 }
		}

	 }
	 if ( mode == 1) // mode 1 is spiral
	 {
			int leftSpeed = 10;
  		int rightSpeed = 40;


  		while( exit == 1)
  		{
		  	motor(left) = leftSpeed;
		  	motor(right) = rightSpeed;


		  	leftSpeed = leftSpeed + 1;
		  	rightSpeed = rightSpeed + 1;
		  	wait1Msec(375);

		  	if (SensorValue(button) == 1 || SensorValue(buttonTwo) == 1)
		  	{
		  		mode = 0;
		  		exit = 0;
		  	}
  		}
	 }

	 if ( mode == 2) // mode two is going out into the world
	 {
	   motor(left) = -defSpeed;
	   motor(right) = -defSpeed;
	   wait1Msec(750);

	   motor(left) = -defSpeed;
		 motor(right) = defSpeed;
		 wait1Msec(960/2);

		 resetMotorEncoder(left);
		 resetMotorEncoder(right);

		 exit = 0;
		 while ( exit == 0)
		 {

		   motor(left) = defSpeed;
		   motor(right) = defSpeed;

       wait1Msec(250);
		   if (SensorValue(button) == 1 || SensorValue(buttonTwo) == 1)
		   {
		     mode = 0;
		     exit = 1;
		   } else if (getMotorEncoder(left) + getMotorEncoder(right) >= 10000)
		   {
		     mode = 1;
		     exit = 1;
		   }


		 }
	 }

 } // end of while

}
